//// Decompiled with JetBrains decompiler
//// Type: TaleWorlds.Core.Equipment
//// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//// MVID: 4282646E-E702-4B98-B76A-B7486FBD2594
//// Assembly location: C:\Users\trist\Documents\Modding\Bannerlord\DLLs\TaleWorlds.Core.dll

//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Xml;
//using TaleWorlds.Library;
//using TaleWorlds.Localization;
//using TaleWorlds.ObjectSystem;
//using TaleWorlds.SaveSystem;

//#nullable disable
//namespace TaleWorlds.Core
//{
//  public class Equipment
//  {
//    [SaveableField(1)]
//    private Equipment.EquipmentType _equipmentType;
//    public const int EquipmentSlotLength = 12;
//    [SaveableField(2)]
//    private readonly EquipmentElement[] _itemSlots;
//    public bool SyncEquipments;
//    public const string NullCode = "@null";

//    internal static void AutoGeneratedStaticCollectObjectsEquipment(
//      object o,
//      List<object> collectedObjects)
//    {
//      ((Equipment) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
//    }

//    protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
//    {
//      collectedObjects.Add((object) this._itemSlots);
//    }

//    internal static object AutoGeneratedGetMemberValue_equipmentType(object o)
//    {
//      return (object) ((Equipment) o)._equipmentType;
//    }

//    internal static object AutoGeneratedGetMemberValue_itemSlots(object o)
//    {
//      return (object) ((Equipment) o)._itemSlots;
//    }

//    public bool IsCivilian => this._equipmentType == Equipment.EquipmentType.Civilian;

//    public bool IsBattle => this._equipmentType == Equipment.EquipmentType.Battle;

//    public bool IsStealth => this._equipmentType == Equipment.EquipmentType.Stealth;

//    public Equipment()
//    {
//      this._itemSlots = new EquipmentElement[12];
//      this._equipmentType = Equipment.EquipmentType.Invalid;
//    }

//    public Equipment(Equipment.EquipmentType equipmentType)
//      : this()
//    {
//      this._itemSlots = new EquipmentElement[12];
//      this._equipmentType = equipmentType;
//    }

//    public Equipment(Equipment equipment)
//    {
//      this._itemSlots = new EquipmentElement[12];
//      for (int index = 0; index < 12; ++index)
//        this._itemSlots[index] = new EquipmentElement(equipment[index]);
//      this._equipmentType = equipment._equipmentType;
//    }

//    public EquipmentElement this[int index]
//    {
//      get => this._itemSlots[index];
//      set
//      {
//        Equipment.IsItemFitsToSlot((EquipmentIndex) index, value.Item);
//        this._itemSlots[index] = value;
//      }
//    }

//    public EquipmentElement this[EquipmentIndex index]
//    {
//      get => this._itemSlots[(int) index];
//      set => this[(int) index] = value;
//    }

//    public EquipmentElement Horse => this._itemSlots[10];

//    private void SetItem(int index, EquipmentElement element) => this[index] = element;

//    public Equipment Clone(bool cloneWithoutWeapons = false)
//    {
//      Equipment equipment = new Equipment(this._equipmentType);
//      for (int index = 0; index < 12; ++index)
//      {
//        bool flag = cloneWithoutWeapons && index >= 0 && index < 5;
//        equipment.SetItem(index, flag ? EquipmentElement.Invalid : this[index]);
//      }
//      return equipment;
//    }

//    public void FillFrom(Equipment sourceEquipment, bool useSourceEquipmentType = true)
//    {
//      if (useSourceEquipmentType)
//        this._equipmentType = sourceEquipment._equipmentType;
//      for (int index = 0; index < 12; ++index)
//        this[index] = sourceEquipment[index];
//    }

//    public void Deserialize(MBObjectManager objectManager, XmlNode node)
//    {
//      foreach (XmlNode childNode in node.ChildNodes)
//        this.DeserializeNode(objectManager, childNode);
//    }

//    public void DeserializeNode(MBObjectManager objectManager, XmlNode node)
//    {
//      if (node.NodeType == XmlNodeType.Comment)
//        return;
//      XmlAttributeCollection attributes = node.Attributes;
//      XmlAttribute xmlAttribute1 = attributes["id"];
//      XmlAttribute xmlAttribute2 = attributes["slot"];
//      string str;
//      if (!xmlAttribute1.Value.Contains("."))
//        str = xmlAttribute1.Value;
//      else
//        str = xmlAttribute1.Value.Split('.')[1];
//      string objectName = str;
//      EquipmentIndex equipmentIndexName = Equipment.GetEquipmentIndexFromOldEquipmentIndexName(xmlAttribute2.Value);
//      ItemObject itemObject = MBObjectManager.Instance.GetObject<ItemObject>(objectName);
//      if (Equipment.IsItemFitsToSlot(equipmentIndexName, itemObject))
//        this[equipmentIndexName] = new EquipmentElement(itemObject);
//      else
//        Debug.FailedAssert((itemObject == null ? (object) TextObject.GetEmpty() : (object) itemObject.Name).ToString() + " does not fit to slot " + (object) equipmentIndexName, "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\Equipment.cs", nameof (DeserializeNode), 169);
//    }

//    public static EquipmentIndex GetEquipmentIndexFromOldEquipmentIndexName(
//      string oldEquipmentIndexName)
//    {
//      string str;
//      switch (oldEquipmentIndexName)
//      {
//        case "Item0":
//          str = "Weapon0";
//          break;
//        case "Item1":
//          str = "Weapon1";
//          break;
//        case "Item2":
//          str = "Weapon2";
//          break;
//        case "Item3":
//          str = "Weapon3";
//          break;
//        case "Item4":
//          str = "ExtraWeaponSlot";
//          break;
//        default:
//          str = oldEquipmentIndexName;
//          break;
//      }
//      return (EquipmentIndex) Enum.Parse(typeof (EquipmentIndex), str);
//    }

//    public bool IsEmpty()
//    {
//      return ((IEnumerable<EquipmentElement>) this._itemSlots).All<EquipmentElement>((Func<EquipmentElement, bool>) (itemRosterElement => itemRosterElement.Item == null));
//    }

//    public float GetTotalWeightOfArmor(bool forHuman)
//    {
//      float totalWeightOfArmor = 0.0f;
//      for (EquipmentIndex index = forHuman ? EquipmentIndex.NumAllWeaponSlots : EquipmentIndex.HorseHarness; index < (forHuman ? EquipmentIndex.ArmorItemEndSlot : EquipmentIndex.NumEquipmentSetSlots); ++index)
//      {
//        EquipmentElement equipmentElement = this[index];
//        if (!equipmentElement.IsEmpty)
//          totalWeightOfArmor += equipmentElement.GetEquipmentElementWeight();
//      }
//      return totalWeightOfArmor;
//    }

//    public float GetTotalWeightOfWeapons()
//    {
//      float totalWeightOfWeapons = 0.0f;
//      for (EquipmentIndex index = EquipmentIndex.WeaponItemBeginSlot; index < EquipmentIndex.NumAllWeaponSlots; ++index)
//      {
//        EquipmentElement equipmentElement = this[index];
//        if (!equipmentElement.IsEmpty)
//          totalWeightOfWeapons += equipmentElement.GetEquipmentElementWeight();
//      }
//      return totalWeightOfWeapons;
//    }

//    public float GetHeadArmorSum()
//    {
//      float headArmorSum = 0.0f;
//      for (EquipmentIndex index = EquipmentIndex.NumAllWeaponSlots; index < EquipmentIndex.ArmorItemEndSlot; ++index)
//      {
//        EquipmentElement equipmentElement = this[index];
//        if (equipmentElement.Item != null)
//          headArmorSum += (float) equipmentElement.GetModifiedHeadArmor();
//      }
//      return headArmorSum;
//    }

//    public float GetHumanBodyArmorSum()
//    {
//      float humanBodyArmorSum = 0.0f;
//      for (EquipmentIndex index = EquipmentIndex.NumAllWeaponSlots; index < EquipmentIndex.ArmorItemEndSlot; ++index)
//      {
//        EquipmentElement equipmentElement = this[index];
//        if (equipmentElement.Item != null)
//          humanBodyArmorSum += (float) equipmentElement.GetModifiedBodyArmor();
//      }
//      return humanBodyArmorSum;
//    }

//    public float GetLegArmorSum()
//    {
//      float legArmorSum = 0.0f;
//      for (EquipmentIndex index = EquipmentIndex.NumAllWeaponSlots; index < EquipmentIndex.ArmorItemEndSlot; ++index)
//      {
//        EquipmentElement equipmentElement = this[index];
//        if (equipmentElement.Item != null)
//          legArmorSum += (float) equipmentElement.GetModifiedLegArmor();
//      }
//      return legArmorSum;
//    }

//    public float GetArmArmorSum()
//    {
//      float armArmorSum = 0.0f;
//      for (EquipmentIndex index = EquipmentIndex.NumAllWeaponSlots; index < EquipmentIndex.ArmorItemEndSlot; ++index)
//      {
//        EquipmentElement equipmentElement = this[index];
//        if (equipmentElement.Item != null)
//          armArmorSum += (float) equipmentElement.GetModifiedArmArmor();
//      }
//      return armArmorSum;
//    }

//    public float GetHorseArmorSum()
//    {
//      float horseArmorSum = 0.0f;
//      EquipmentElement equipmentElement = this[EquipmentIndex.HorseHarness];
//      if (equipmentElement.Item != null)
//        horseArmorSum += (float) equipmentElement.GetModifiedMountBodyArmor();
//      return horseArmorSum;
//    }

//    public ArmorComponent.HairCoverTypes HairCoverType
//    {
//      get
//      {
//        ArmorComponent.HairCoverTypes hairCoverType = ArmorComponent.HairCoverTypes.None;
//        ItemObject itemObject = this[EquipmentIndex.NumAllWeaponSlots].Item;
//        if (itemObject != null)
//        {
//          ArmorComponent armorComponent = itemObject.ArmorComponent;
//          hairCoverType = armorComponent != null ? armorComponent.HairCoverType : ArmorComponent.HairCoverTypes.None;
//        }
//        else if (this[EquipmentIndex.Body].Item == null)
//          hairCoverType = ArmorComponent.HairCoverTypes.Type4;
//        return hairCoverType;
//      }
//    }

//    public ArmorComponent.BeardCoverTypes BeardCoverType
//    {
//      get
//      {
//        return this[EquipmentIndex.NumAllWeaponSlots].Item?.ArmorComponent?.BeardCoverType ?? ArmorComponent.BeardCoverTypes.None;
//      }
//    }

//    public ArmorComponent.HorseHarnessCoverTypes ManeCoverType
//    {
//      get
//      {
//        return this[EquipmentIndex.HorseHarness].Item?.ArmorComponent?.ManeCoverType ?? ArmorComponent.HorseHarnessCoverTypes.None;
//      }
//    }

//    public string ReinsMeshName
//    {
//      get => this[EquipmentIndex.HorseHarness].Item?.ArmorComponent?.ReinsMesh ?? "";
//    }

//    public bool EarsAreHidden
//    {
//      get
//      {
//        return this.HairCoverType != ArmorComponent.HairCoverTypes.None && this.HairCoverType != ArmorComponent.HairCoverTypes.Type1 && this.HairCoverType != ArmorComponent.HairCoverTypes.Type4;
//      }
//    }

//    public bool MouthIsHidden => this.BeardCoverType == ArmorComponent.BeardCoverTypes.All;

//    public ArmorComponent.BodyMeshTypes BodyMeshType
//    {
//      get
//      {
//        return this[EquipmentIndex.Body].Item?.ArmorComponent?.BodyMeshType ?? ArmorComponent.BodyMeshTypes.Normal;
//      }
//    }

//    public ArmorComponent.BodyDeformTypes BodyDeformType
//    {
//      get
//      {
//        return this[EquipmentIndex.Body].Item?.ArmorComponent?.BodyDeformType ?? ArmorComponent.BodyDeformTypes.Medium;
//      }
//    }

//    public Equipment.UnderwearTypes GetUnderwearType(bool isFemale)
//    {
//      ItemObject itemObject = this[EquipmentIndex.Body].Item;
//      return itemObject != null ? (!isFemale || !itemObject.DoesNotHideChest ? Equipment.UnderwearTypes.NoUnderwear : Equipment.UnderwearTypes.OnlyTop) : Equipment.UnderwearTypes.FullUnderwear;
//    }

//    public bool HasWeapon()
//    {
//      for (int index = 0; index < 5; ++index)
//      {
//        EquipmentElement itemSlot = this._itemSlots[index];
//        if (!itemSlot.IsEmpty && itemSlot.Item.PrimaryWeapon.WeaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.WeaponMask))
//          return true;
//      }
//      return false;
//    }

//    public bool HasWeaponOfClass(WeaponClass weaponClass)
//    {
//      for (int index = 0; index < 5; ++index)
//      {
//        EquipmentElement itemSlot = this._itemSlots[index];
//        if (!itemSlot.IsEmpty && itemSlot.Item.PrimaryWeapon.WeaponClass == weaponClass)
//          return true;
//      }
//      return false;
//    }

//    public static Equipment CreateFromEquipmentCode(string equipmentCode)
//    {
//      Equipment fromEquipmentCode = new Equipment();
//      for (int index = 0; index < 12; ++index)
//        fromEquipmentCode[index] = new EquipmentElement();
//      string str1 = equipmentCode;
//      char[] separator1 = new char[1]{ '+' };
//      foreach (string str2 in str1.Split(separator1, StringSplitOptions.RemoveEmptyEntries))
//      {
//        char[] separator2 = new char[1]{ '-' };
//        string[] strArray = str2.Split(separator2, StringSplitOptions.RemoveEmptyEntries);
//        int int32 = Convert.ToInt32(strArray[0]);
//        string objectName1 = strArray[1];
//        if (objectName1 != "@null")
//        {
//          ItemObject itemObject = MBObjectManager.Instance.GetObject<ItemObject>(objectName1);
//          string objectName2 = strArray[2];
//          ItemModifier itemModifier = (ItemModifier) null;
//          if (objectName2 != "@null")
//            itemModifier = MBObjectManager.Instance.GetObject<ItemModifier>(objectName2);
//          EquipmentElement equipmentElement = new EquipmentElement(itemObject, itemModifier);
//          fromEquipmentCode[int32] = equipmentElement;
//        }
//      }
//      return fromEquipmentCode;
//    }

//    public string CalculateEquipmentCode()
//    {
//      MBStringBuilder mbStringBuilder = new MBStringBuilder();
//      mbStringBuilder.Initialize(callerMemberName: nameof (CalculateEquipmentCode));
//      for (int index = 0; index < 12; ++index)
//      {
//        EquipmentElement equipmentElement = this[index];
//        string str1 = equipmentElement.Item != null ? equipmentElement.Item.StringId : "@null";
//        string str2 = equipmentElement.ItemModifier != null ? equipmentElement.ItemModifier.StringId : "@null";
//        if (string.IsNullOrEmpty(str1))
//          str1 = "@null";
//        if (string.IsNullOrEmpty(str2))
//          str2 = "@null";
//        mbStringBuilder.Append('+');
//        mbStringBuilder.Append(index);
//        mbStringBuilder.Append('-');
//        mbStringBuilder.Append<string>(str1);
//        mbStringBuilder.Append('-');
//        mbStringBuilder.Append<string>(str2);
//      }
//      return mbStringBuilder.ToStringAndRelease();
//    }

//    public void AddEquipmentToSlotWithoutAgent(
//      EquipmentIndex equipmentIndex,
//      EquipmentElement itemRosterElement)
//    {
//      this[equipmentIndex] = itemRosterElement;
//    }

//    public EquipmentElement GetEquipmentFromSlot(EquipmentIndex equipmentIndex)
//    {
//      return this[equipmentIndex];
//    }

//    public static bool IsItemFitsToSlot(EquipmentIndex slotIndex, ItemObject item)
//    {
//      bool slot = false;
//      if (item == null)
//      {
//        slot = true;
//      }
//      else
//      {
//        switch (item.ItemType)
//        {
//          case ItemObject.ItemTypeEnum.Invalid:
//            slot = false;
//            break;
//          case ItemObject.ItemTypeEnum.Horse:
//            slot = slotIndex == EquipmentIndex.ArmorItemEndSlot;
//            break;
//          case ItemObject.ItemTypeEnum.OneHandedWeapon:
//          case ItemObject.ItemTypeEnum.TwoHandedWeapon:
//          case ItemObject.ItemTypeEnum.Polearm:
//          case ItemObject.ItemTypeEnum.Arrows:
//          case ItemObject.ItemTypeEnum.Bolts:
//          case ItemObject.ItemTypeEnum.SlingStones:
//          case ItemObject.ItemTypeEnum.Shield:
//          case ItemObject.ItemTypeEnum.Bow:
//          case ItemObject.ItemTypeEnum.Crossbow:
//          case ItemObject.ItemTypeEnum.Sling:
//          case ItemObject.ItemTypeEnum.Thrown:
//          case ItemObject.ItemTypeEnum.Pistol:
//          case ItemObject.ItemTypeEnum.Musket:
//          case ItemObject.ItemTypeEnum.Bullets:
//          case ItemObject.ItemTypeEnum.Banner:
//            slot = !item.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.DropOnWeaponChange | ItemFlags.DropOnAnyAction) ? slotIndex == EquipmentIndex.WeaponItemBeginSlot || slotIndex == EquipmentIndex.Weapon1 || slotIndex == EquipmentIndex.Weapon2 || slotIndex == EquipmentIndex.Weapon3 : slotIndex == EquipmentIndex.ExtraWeaponSlot;
//            break;
//          case ItemObject.ItemTypeEnum.HeadArmor:
//            slot = slotIndex == EquipmentIndex.NumAllWeaponSlots;
//            break;
//          case ItemObject.ItemTypeEnum.BodyArmor:
//            slot = slotIndex == EquipmentIndex.Body;
//            break;
//          case ItemObject.ItemTypeEnum.LegArmor:
//            slot = slotIndex == EquipmentIndex.Leg;
//            break;
//          case ItemObject.ItemTypeEnum.HandArmor:
//            slot = slotIndex == EquipmentIndex.Gloves;
//            break;
//          case ItemObject.ItemTypeEnum.Animal:
//            slot = slotIndex == EquipmentIndex.ArmorItemEndSlot;
//            break;
//          case ItemObject.ItemTypeEnum.Book:
//            slot = false;
//            break;
//          case ItemObject.ItemTypeEnum.Cape:
//            slot = slotIndex == EquipmentIndex.Cape;
//            break;
//          case ItemObject.ItemTypeEnum.HorseHarness:
//            slot = slotIndex == EquipmentIndex.HorseHarness;
//            break;
//        }
//      }
//      return slot;
//    }

//    public EquipmentIndex GetWeaponPickUpSlotIndex(
//      EquipmentElement itemRosterElement,
//      bool isStuckMissile)
//    {
//      if (itemRosterElement.Item.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.DropOnWeaponChange | ItemFlags.DropOnAnyAction))
//        return EquipmentIndex.ExtraWeaponSlot;
//      EquipmentIndex weaponPickUpSlotIndex = EquipmentIndex.None;
//      if (weaponPickUpSlotIndex == EquipmentIndex.None)
//      {
//        for (EquipmentIndex index = EquipmentIndex.WeaponItemBeginSlot; index < EquipmentIndex.ExtraWeaponSlot; ++index)
//        {
//          if (this[(int) index].Item == null)
//          {
//            weaponPickUpSlotIndex = index;
//            break;
//          }
//        }
//      }
//      return weaponPickUpSlotIndex;
//    }

//    public bool IsEquipmentEqualTo(Equipment other)
//    {
//      if (other == null)
//        return false;
//      for (int index = 0; index < 12; ++index)
//      {
//        if (!this[index].IsEqualTo(other[index]))
//          return false;
//      }
//      return other.IsStealth == this.IsStealth && other.IsCivilian == this.IsCivilian && other.IsBattle == this.IsBattle;
//    }

//    public static Equipment GetRandomEquipmentElements(
//      BasicCharacterObject character,
//      bool randomEquipmentModifier,
//      Equipment.EquipmentType equipmentType,
//      int seed = -1)
//    {
//      Equipment equipmentElements = new Equipment(equipmentType);
//      List<Equipment> equipmentList = new List<Equipment>();
//      switch (equipmentType)
//      {
//        case Equipment.EquipmentType.Battle:
//          equipmentList = character.BattleEquipments.ToList<Equipment>();
//          break;
//        case Equipment.EquipmentType.Civilian:
//          equipmentList = character.CivilianEquipments.ToList<Equipment>();
//          break;
//      }
//      if (equipmentList.IsEmpty<Equipment>())
//        return equipmentElements;
//      int count = equipmentList.Count;
//      Random random = new Random(seed);
//      int weaponSetNo1 = MBRandom.RandomInt(count);
//      int weaponSetNo2 = MBRandom.RandomInt(count);
//      int weaponSetNo3 = MBRandom.RandomInt(count);
//      for (int index = 0; index < 12; ++index)
//      {
//        if (seed != -1)
//        {
//          weaponSetNo1 = random.Next() % count;
//          weaponSetNo2 = random.Next() % count;
//          weaponSetNo3 = random.Next() % count;
//        }
//        switch (index)
//        {
//          case 0:
//          case 1:
//            equipmentElements[index] = Equipment.GetRandomizedEquipment(equipmentList, (EquipmentIndex) index, weaponSetNo1, randomEquipmentModifier);
//            break;
//          case 2:
//          case 3:
//            equipmentElements[index] = Equipment.GetRandomizedEquipment(equipmentList, (EquipmentIndex) index, weaponSetNo2, randomEquipmentModifier);
//            break;
//          default:
//            equipmentElements[index] = Equipment.GetRandomizedEquipment(equipmentList, (EquipmentIndex) index, weaponSetNo3, randomEquipmentModifier);
//            break;
//        }
//      }
//      return equipmentElements;
//    }

//    public static void SwapWeapons(
//      Equipment equipment,
//      EquipmentIndex index1,
//      EquipmentIndex index2)
//    {
//      EquipmentElement equipmentElement = equipment[index1];
//      equipment[index1] = equipment[index2];
//      equipment[index2] = equipmentElement;
//    }

//    private static EquipmentElement GetRandomizedEquipment(
//      List<Equipment> equipmentSets,
//      EquipmentIndex weaponSlot,
//      int weaponSetNo,
//      bool randomEquipmentModifier)
//    {
//      EquipmentElement equipmentFromSlot = equipmentSets[weaponSetNo].GetEquipmentFromSlot(weaponSlot);
//      if (randomEquipmentModifier)
//      {
//        ItemModifier modifierLootScoreBased = equipmentFromSlot.Item?.ItemComponent?.ItemModifierGroup?.GetRandomItemModifierLootScoreBased();
//        if (modifierLootScoreBased != null)
//          equipmentFromSlot.SetModifier(modifierLootScoreBased);
//      }
//      return equipmentFromSlot;
//    }

//    public void GetInitialWeaponIndicesToEquip(
//      out EquipmentIndex mainHandWeaponIndex,
//      out EquipmentIndex offHandWeaponIndex,
//      out bool isMainHandNotUsableWithOneHand,
//      Equipment.InitialWeaponEquipPreference initialWeaponEquipPreference = Equipment.InitialWeaponEquipPreference.Any)
//    {
//      mainHandWeaponIndex = EquipmentIndex.None;
//      offHandWeaponIndex = EquipmentIndex.None;
//      isMainHandNotUsableWithOneHand = false;
//      EquipmentIndex[] equipmentIndexArray = new EquipmentIndex[5]
//      {
//        EquipmentIndex.ExtraWeaponSlot,
//        EquipmentIndex.WeaponItemBeginSlot,
//        EquipmentIndex.Weapon1,
//        EquipmentIndex.Weapon2,
//        EquipmentIndex.Weapon3
//      };
//      bool flag1 = false;
//      bool flag2 = false;
//      for (int index1 = 0; index1 < equipmentIndexArray.Length; ++index1)
//      {
//        EquipmentIndex index2 = equipmentIndexArray[index1];
//        EquipmentElement equipmentElement = this[index2];
//        if (!equipmentElement.IsEmpty)
//        {
//          equipmentElement = this[index2];
//          ItemObject itemObject = equipmentElement.Item;
//          if ((mainHandWeaponIndex == EquipmentIndex.None || initialWeaponEquipPreference == Equipment.InitialWeaponEquipPreference.MeleeForMainHand && !flag1 || initialWeaponEquipPreference == Equipment.InitialWeaponEquipPreference.RangedForMainHand && !flag2) && !itemObject.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.HeldInOffHand))
//          {
//            mainHandWeaponIndex = index2;
//            isMainHandNotUsableWithOneHand = itemObject.PrimaryWeapon.WeaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.NotUsableWithOneHand);
//            flag1 = itemObject.PrimaryWeapon.WeaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.MeleeWeapon);
//            flag2 = itemObject.PrimaryWeapon.WeaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.RangedWeapon);
//          }
//          else if (offHandWeaponIndex == EquipmentIndex.None && itemObject.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.HeldInOffHand))
//            offHandWeaponIndex = index2;
//        }
//      }
//    }

//    public enum EquipmentType
//    {
//      Invalid = -1, // 0xFFFFFFFF
//      Battle = 0,
//      Civilian = 1,
//      Stealth = 2,
//    }

//    public enum UnderwearTypes
//    {
//      NoUnderwear,
//      FullUnderwear,
//      OnlyTop,
//    }

//    public enum InitialWeaponEquipPreference
//    {
//      Any,
//      MeleeForMainHand,
//      RangedForMainHand,
//    }
//  }
//}
