//// Decompiled with JetBrains decompiler
//// Type: TaleWorlds.Core.ItemObject
//// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//// MVID: 4282646E-E702-4B98-B76A-B7486FBD2594
//// Assembly location: C:\Users\trist\Documents\Modding\Bannerlord\DLLs\TaleWorlds.Core.dll

//using System;
//using System.Collections.Generic;
//using System.Diagnostics;
//using System.Globalization;
//using System.Linq;
//using System.Xml;
//using TaleWorlds.Library;
//using TaleWorlds.Localization;
//using TaleWorlds.ObjectSystem;

//#nullable disable
//namespace TaleWorlds.Core
//{
//  public sealed class ItemObject : MBObjectBase
//  {
//    public const float DefaultAppearanceValue = 0.5f;
//    public const int MaxHolsterSlotCount = 4;
//    private const float TierfOverrideAdjustmentValue = 1f;
//    public ItemObject.ItemTypeEnum Type;

//    internal static void AutoGeneratedStaticCollectObjectsItemObject(
//      object o,
//      List<object> collectedObjects)
//    {
//      ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
//    }

//    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
//    {
//      base.AutoGeneratedInstanceCollectObjects(collectedObjects);
//    }

//    public ItemComponent ItemComponent { get; private set; }

//    public string MultiMeshName { get; private set; }

//    public string HolsterMeshName { get; private set; }

//    public string HolsterWithWeaponMeshName { get; private set; }

//    public string[] ItemHolsters { get; private set; }

//    public Vec3 HolsterPositionShift { get; private set; }

//    public bool HasLowerHolsterPriority { get; private set; }

//    public string FlyingMeshName { get; private set; }

//    public string BodyName { get; private set; }

//    public string SkeletonName { get; private set; }

//    public string StaticAnimationName { get; private set; }

//    public string HolsterBodyName { get; private set; }

//    public string CollisionBodyName { get; private set; }

//    public bool RecalculateBody { get; private set; }

//    public string PrefabName { get; private set; }

//    public TextObject Name { get; private set; }

//    public ItemFlags ItemFlags { get; private set; }

//    public ItemCategory ItemCategory { get; private set; }

//    public int Value { get; private set; }

//    public float Effectiveness { get; private set; }

//    public float Weight { get; private set; }

//    public int Difficulty { get; private set; }

//    public float Appearance { get; private set; }

//    public bool IsUsingTableau { get; private set; }

//    public bool IsUsingTeamColor => this.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.UseTeamColor);

//    public bool DoesNotHideChest
//    {
//      get => this.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.DoesNotHideChest);
//    }

//    public bool IsCivilian => this.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.Civilian);

//    public bool IsStealthItem => this.ItemFlags.HasAnyFlag<ItemFlags>(ItemFlags.Stealth);

//    public bool UsingFacegenScaling
//    {
//      get
//      {
//        return this.Type == ItemObject.ItemTypeEnum.HeadArmor && this.ArmorComponent.MeshesMask.HasAnyFlag<SkinMask>(SkinMask.HeadVisible);
//      }
//    }

//    public string ArmBandMeshName { get; private set; }

//    public bool IsFood { get; private set; }

//    public float ScaleFactor { get; private set; }

//    public BasicCultureObject Culture { get; private set; }

//    public bool MultiplayerItem { get; private set; }

//    public bool NotMerchandise { get; private set; }

//    public bool IsCraftedByPlayer { get; private set; }

//    public int LodAtlasIndex { get; private set; }

//    private float TierfOverride { get; set; }

//    public bool IsTransferable => Game.Current.BasicModels.ItemValueModel.GetIsTransferable(this);

//    public float Tierf
//    {
//      get
//      {
//        return (double) this.TierfOverride >= 1.0 ? this.TierfOverride - 1f : Game.Current.BasicModels.ItemValueModel.CalculateTier(this);
//      }
//    }

//    public bool IsCraftedWeapon => this.WeaponDesign != (WeaponDesign) null;

//    public ItemObject.ItemTiers Tier
//    {
//      get
//      {
//        return this.ItemComponent == null ? ItemObject.ItemTiers.Tier1 : (ItemObject.ItemTiers) (MBMath.ClampInt(MathF.Round(this.Tierf), 0, 6) - 1);
//      }
//    }

//    public WeaponDesign WeaponDesign { get; private set; }

//    public WeaponComponentData PrimaryWeapon => this.WeaponComponent?.PrimaryWeapon;

//    public WeaponComponent WeaponComponent => this.ItemComponent as WeaponComponent;

//    public bool HasWeaponComponent => this.WeaponComponent != null;

//    public HorseComponent HorseComponent => this.ItemComponent as HorseComponent;

//    public bool HasHorseComponent => this.HorseComponent != null;

//    public ArmorComponent ArmorComponent => this.ItemComponent as ArmorComponent;

//    public bool HasArmorComponent => this.ArmorComponent != null;

//    public BannerComponent BannerComponent => this.ItemComponent as BannerComponent;

//    public bool HasBannerComponent => this.BannerComponent != null;

//    public SaddleComponent SaddleComponent => this.ItemComponent as SaddleComponent;

//    public bool HasSaddleComponent => this.SaddleComponent != null;

//    public TradeItemComponent FoodComponent => this.ItemComponent as TradeItemComponent;

//    public bool HasFoodComponent => this.FoodComponent != null;

//    public ItemObject()
//    {
//    }

//    public ItemObject(string stringId)
//      : base(stringId)
//    {
//    }

//    public ItemObject(ItemObject itemToCopy)
//      : base((MBObjectBase) itemToCopy)
//    {
//      this.ItemComponent = itemToCopy.ItemComponent;
//      this.MultiMeshName = itemToCopy.MultiMeshName;
//      this.HolsterMeshName = itemToCopy.HolsterMeshName;
//      this.HolsterWithWeaponMeshName = itemToCopy.HolsterWithWeaponMeshName;
//      this.ItemHolsters = itemToCopy.ItemHolsters;
//      this.HolsterPositionShift = itemToCopy.HolsterPositionShift;
//      this.FlyingMeshName = itemToCopy.FlyingMeshName;
//      this.BodyName = itemToCopy.BodyName;
//      this.SkeletonName = itemToCopy.SkeletonName;
//      this.StaticAnimationName = itemToCopy.StaticAnimationName;
//      this.HolsterBodyName = itemToCopy.HolsterBodyName;
//      this.CollisionBodyName = itemToCopy.CollisionBodyName;
//      this.RecalculateBody = itemToCopy.RecalculateBody;
//      this.PrefabName = itemToCopy.PrefabName;
//      this.Name = itemToCopy.Name;
//      this.ItemFlags = itemToCopy.ItemFlags;
//      this.Value = itemToCopy.Value;
//      this.Weight = itemToCopy.Weight;
//      this.Difficulty = itemToCopy.Difficulty;
//      this.ArmBandMeshName = itemToCopy.ArmBandMeshName;
//      this.IsFood = itemToCopy.IsFood;
//      this.Type = itemToCopy.Type;
//      this.ScaleFactor = itemToCopy.ScaleFactor;
//    }

//    internal void SetCraftedWeaponName(TextObject weaponName)
//    {
//      this.Name = weaponName;
//      if (!(this.WeaponDesign != (WeaponDesign) null))
//        return;
//      this.WeaponDesign.SetWeaponName(this.Name);
//    }

//    public static ItemObject InitializeTradeGood(
//      ItemObject item,
//      TextObject name,
//      string meshName,
//      ItemCategory category,
//      int value,
//      float weight,
//      ItemObject.ItemTypeEnum itemType,
//      bool isFood = false)
//    {
//      item.Initialize();
//      item.Name = name;
//      item.MultiMeshName = meshName;
//      item.ItemCategory = category;
//      item.Value = value;
//      item.Weight = weight;
//      item.ItemType = itemType;
//      item.IsFood = isFood;
//      item.ItemComponent = (ItemComponent) new TradeItemComponent();
//      item.AfterInitialized();
//      item.ItemFlags |= ItemFlags.Civilian;
//      return item;
//    }

//    public static void InitAsPlayerCraftedItem(ref ItemObject itemObject)
//    {
//      itemObject.IsCraftedByPlayer = true;
//    }

//    internal static void InitCraftedItemObject(
//      ref ItemObject itemObject,
//      TextObject name,
//      BasicCultureObject culture,
//      ItemFlags itemProperties,
//      float weight,
//      float appearance,
//      WeaponDesign craftedData,
//      ItemObject.ItemTypeEnum itemType)
//    {
//      BladeData bladeData = craftedData.UsedPieces[0].CraftingPiece.BladeData;
//      itemObject.Weight = weight;
//      itemObject.Name = name;
//      itemObject.MultiMeshName = "";
//      itemObject.HolsterMeshName = "";
//      itemObject.HolsterWithWeaponMeshName = "";
//      itemObject.ItemHolsters = (string[]) craftedData.Template.ItemHolsters.Clone();
//      itemObject.HolsterPositionShift = craftedData.HolsterShiftAmount;
//      itemObject.FlyingMeshName = "";
//      itemObject.BodyName = bladeData?.BodyName;
//      itemObject.HolsterBodyName = bladeData?.HolsterBodyName ?? bladeData?.BodyName;
//      itemObject.CollisionBodyName = "";
//      itemObject.RecalculateBody = true;
//      itemObject.Culture = culture;
//      itemObject.Difficulty = 0;
//      itemObject.ScaleFactor = 1f;
//      itemObject.Type = itemType;
//      itemObject.ItemFlags = itemProperties;
//      itemObject.Appearance = appearance;
//      itemObject.WeaponDesign = craftedData;
//    }

//    public override int GetHashCode() => (int) this.Id.SubId;

//    public void SetItemFlagsForCosmetics(ItemFlags newFlags) => this.ItemFlags = newFlags;

//    public void DetermineItemCategoryForItem()
//    {
//      if (Game.Current.BasicModels.ItemCategorySelector == null || this.ItemCategory != null)
//        return;
//      this.ItemCategory = Game.Current.BasicModels.ItemCategorySelector.GetItemCategoryForItem(this);
//    }

//    public static ItemObject GetCraftedItemObjectFromHashedCode(string hashedCode)
//    {
//      foreach (ItemObject objectType in (List<ItemObject>) MBObjectManager.Instance.GetObjectTypeList<ItemObject>())
//      {
//        if (objectType.IsCraftedWeapon && objectType.WeaponDesign.HashedCode == hashedCode)
//          return objectType;
//      }
//      return (ItemObject) null;
//    }

//    public MBReadOnlyList<WeaponComponentData> Weapons => this.WeaponComponent?.Weapons;

//    public void AddWeapon(WeaponComponentData weapon, ItemModifierGroup itemModifierGroup)
//    {
//      if (this.WeaponComponent == null)
//        this.ItemComponent = (ItemComponent) new WeaponComponent(this);
//      this.WeaponComponent.AddWeapon(weapon, itemModifierGroup);
//    }

//    public override void Deserialize(MBObjectManager objectManager, XmlNode node)
//    {
//      base.Deserialize(objectManager, node);
//      if (node.Name == "CraftedItem")
//      {
//        XmlNode attribute1 = (XmlNode) node.Attributes["multiplayer_item"];
//        if (attribute1 != null && !string.IsNullOrEmpty(attribute1.InnerText))
//          this.MultiplayerItem = attribute1.InnerText == "true";
//        XmlNode attribute2 = (XmlNode) node.Attributes["is_merchandise"];
//        if (attribute2 != null && !string.IsNullOrEmpty(attribute2.InnerText))
//          this.NotMerchandise = attribute2.InnerText != "true";
//        TextObject craftedWeaponName = new TextObject(node.Attributes["name"].InnerText);
//        string innerText1 = node.Attributes["crafting_template"].InnerText;
//        int num = node.Attributes["has_modifier"] == null ? 1 : (node.Attributes["has_modifier"].InnerText != "false" ? 1 : 0);
//        string objectName = node.Attributes["modifier_group"]?.Value;
//        ItemModifierGroup itemModifierGroup = (ItemModifierGroup) null;
//        if (num != 0)
//          itemModifierGroup = objectName != null ? Game.Current.ObjectManager.GetObject<ItemModifierGroup>(objectName) : CraftingTemplate.GetTemplateFromId(innerText1).ItemModifierGroup;
//        WeaponDesignElement[] usedPieces = new WeaponDesignElement[4];
//        XmlNode xmlNode = (XmlNode) null;
//        for (int i = 0; i < node.ChildNodes.Count; ++i)
//        {
//          if (node.ChildNodes[i].Name == "Pieces")
//          {
//            xmlNode = node.ChildNodes[i];
//            break;
//          }
//        }
//        foreach (XmlNode childNode in xmlNode.ChildNodes)
//        {
//          if (childNode.Name == "Piece")
//          {
//            XmlAttribute attribute3 = childNode.Attributes["id"];
//            XmlAttribute attribute4 = childNode.Attributes["Type"];
//            XmlAttribute attribute5 = childNode.Attributes["scale_factor"];
//            string innerText2 = attribute3.InnerText;
//            CraftingPiece.PieceTypes index = (CraftingPiece.PieceTypes) Enum.Parse(typeof (CraftingPiece.PieceTypes), attribute4.InnerText);
//            CraftingPiece craftingPiece = MBObjectManager.Instance.GetObject<CraftingPiece>(innerText2);
//            usedPieces[(int) index] = WeaponDesignElement.CreateUsablePiece(craftingPiece);
//            if (attribute5 != null)
//              usedPieces[(int) index].SetScale(int.Parse(attribute5.Value));
//          }
//        }
//        ItemObject weaponOnDeserialize = Crafting.CreatePreCraftedWeaponOnDeserialize(this, usedPieces, innerText1, craftedWeaponName, itemModifierGroup);
//        if (weaponOnDeserialize.WeaponComponent == null)
//        {
//          TaleWorlds.Library.Debug.FailedAssert("Crafted item: " + weaponOnDeserialize.StringId + " can not be initialized, item replaced with Trash item.", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (Deserialize), 446);
//          MBObjectManager.Instance.UnregisterObject((MBObjectBase) this);
//          return;
//        }
//        this.Effectiveness = this.CalculateEffectiveness();
//        if (node.Attributes["value"] != null)
//          this.Value = int.Parse(node.Attributes["value"].Value);
//        else
//          this.DetermineValue();
//        if (node.Attributes["culture"] != null)
//          this.Culture = (BasicCultureObject) objectManager.ReadObjectReferenceFromXml("culture", typeof (BasicCultureObject), node);
//      }
//      else
//      {
//        this.Name = new TextObject(node.Attributes["name"].InnerText);
//        XmlNode attribute6 = (XmlNode) node.Attributes["multiplayer_item"];
//        if (attribute6 != null && !string.IsNullOrEmpty(attribute6.InnerText))
//          this.MultiplayerItem = attribute6.InnerText == "true";
//        XmlNode attribute7 = (XmlNode) node.Attributes["is_merchandise"];
//        if (attribute7 != null && !string.IsNullOrEmpty(attribute7.InnerText))
//          this.NotMerchandise = attribute7.InnerText != "true";
//        XmlNode attribute8 = (XmlNode) node.Attributes["mesh"];
//        if (attribute8 != null && !string.IsNullOrEmpty(attribute8.InnerText))
//          this.MultiMeshName = attribute8.InnerText;
//        this.HolsterMeshName = node.Attributes["holster_mesh"] != null ? node.Attributes["holster_mesh"].Value : (string) null;
//        this.HolsterWithWeaponMeshName = node.Attributes["holster_mesh_with_weapon"] != null ? node.Attributes["holster_mesh_with_weapon"].Value : (string) null;
//        this.FlyingMeshName = node.Attributes["flying_mesh"] != null ? node.Attributes["flying_mesh"].Value : (string) null;
//        this.HasLowerHolsterPriority = false;
//        if (node.Attributes["item_holsters"] != null)
//        {
//          this.ItemHolsters = node.Attributes["item_holsters"].Value.Split(':');
//          if (node.Attributes["has_lower_holster_priority"] != null)
//            this.HasLowerHolsterPriority = bool.Parse(node.Attributes["has_lower_holster_priority"].Value);
//        }
//        else
//          this.ItemHolsters = new string[4];
//        this.HolsterPositionShift = node.Attributes["holster_position_shift"] != null ? Vec3.Parse(node.Attributes["holster_position_shift"].Value) : Vec3.Zero;
//        this.BodyName = node.Attributes["body_name"] != null ? node.Attributes["body_name"].Value : (string) null;
//        this.SkeletonName = node.Attributes["skeleton_name"] != null ? node.Attributes["skeleton_name"].Value : (string) null;
//        this.StaticAnimationName = node.Attributes["static_animation_name"] != null ? node.Attributes["static_animation_name"].Value : (string) null;
//        this.HolsterBodyName = node.Attributes["holster_body_name"] != null ? node.Attributes["holster_body_name"].Value : (string) null;
//        this.CollisionBodyName = node.Attributes["shield_body_name"] != null ? node.Attributes["shield_body_name"].Value : (string) null;
//        this.RecalculateBody = node.Attributes["recalculate_body"] != null && bool.Parse(node.Attributes["recalculate_body"].Value);
//        XmlNode attribute9 = (XmlNode) node.Attributes["prefab"];
//        this.PrefabName = attribute9 == null || string.IsNullOrEmpty(attribute9.InnerText) ? "" : attribute9.InnerText;
//        this.Culture = (BasicCultureObject) objectManager.ReadObjectReferenceFromXml("culture", typeof (BasicCultureObject), node);
//        string objectName = node.Attributes["item_category"] != null ? node.Attributes["item_category"].Value : (string) null;
//        if (!string.IsNullOrEmpty(objectName))
//          this.ItemCategory = Game.Current.ObjectManager.GetObject<ItemCategory>(objectName);
//        this.Weight = node.Attributes["weight"] != null ? float.Parse(node.Attributes["weight"].Value) : 1f;
//        this.LodAtlasIndex = node.Attributes["lod_atlas_index"] != null ? int.Parse(node.Attributes["lod_atlas_index"].Value) : -1;
//        XmlAttribute attribute10 = node.Attributes["difficulty"];
//        if (attribute10 != null)
//          this.Difficulty = int.Parse(attribute10.Value);
//        XmlAttribute attribute11 = node.Attributes["appearance"];
//        this.Appearance = attribute11 != null ? float.Parse(attribute11.Value) : 0.5f;
//        XmlAttribute attribute12 = node.Attributes["IsFood"];
//        if (attribute12 != null)
//          this.IsFood = Convert.ToBoolean(attribute12.InnerText);
//        this.IsUsingTableau = node.Attributes["using_tableau"] != null && Convert.ToBoolean(node.Attributes["using_tableau"].InnerText);
//        XmlNode attribute13 = (XmlNode) node.Attributes["using_arm_band"];
//        if (attribute13 != null)
//          this.ArmBandMeshName = Convert.ToString(attribute13.InnerText);
//        this.ScaleFactor = node.Attributes["scale_factor"] != null ? float.Parse(node.Attributes["scale_factor"].Value) : 1f;
//        this.ItemFlags = (ItemFlags) 0;
//        foreach (XmlNode childNode1 in node.ChildNodes)
//        {
//          if (childNode1.Name == "ItemComponent")
//          {
//            foreach (XmlNode childNode2 in childNode1.ChildNodes)
//            {
//              if (childNode2.NodeType != XmlNodeType.Comment)
//              {
//                ItemComponent itemComponent;
//                switch (childNode2.Name)
//                {
//                  case "Armor":
//                    itemComponent = (ItemComponent) new ArmorComponent(this);
//                    break;
//                  case "Weapon":
//                    itemComponent = this.ItemComponent ?? (ItemComponent) new WeaponComponent(this);
//                    break;
//                  case "Horse":
//                    itemComponent = (ItemComponent) new HorseComponent();
//                    break;
//                  case "Trade":
//                    itemComponent = (ItemComponent) new TradeItemComponent();
//                    break;
//                  case "Food":
//                    TaleWorlds.Library.Debug.FailedAssert("FoodComponent tag has been converted to TradeComponent. Use Trade xml node type", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (Deserialize), 685);
//                    itemComponent = (ItemComponent) null;
//                    break;
//                  case "Banner":
//                    itemComponent = (ItemComponent) new BannerComponent(this);
//                    break;
//                  default:
//                    throw new Exception("Wrong ItemComponent type.");
//                }
//                if (itemComponent != null)
//                {
//                  itemComponent.Deserialize(objectManager, childNode2);
//                  this.ItemComponent = itemComponent;
//                }
//              }
//            }
//          }
//          else if (childNode1.Name == "Flags")
//          {
//            foreach (ItemFlags itemFlags in Enum.GetValues(typeof (ItemFlags)))
//            {
//              XmlAttribute attribute14 = childNode1.Attributes[itemFlags.ToString()];
//              if (attribute14 != null && attribute14.Value.ToLowerInvariant() != "false")
//                this.ItemFlags |= itemFlags;
//            }
//          }
//        }
//        XmlAttribute attribute15 = node.Attributes["Type"];
//        if (attribute15 != null)
//        {
//          this.Type = (ItemObject.ItemTypeEnum) Enum.Parse(typeof (ItemObject.ItemTypeEnum), attribute15.Value, true);
//          if (this.WeaponComponent != null)
//          {
//            ItemObject.ItemTypeEnum itemType = this.WeaponComponent.GetItemType();
//            if (this.Type != itemType)
//              TaleWorlds.Library.Debug.Print("ItemType for \"" + this.StringId + "\" has been overridden by WeaponClass from \"" + (object) this.Type + "\" to \"" + (object) itemType + "\"", color: TaleWorlds.Library.Debug.DebugColor.Red, debugFilter: 64UL);
//            this.Type = itemType;
//          }
//        }
//        if (this.Type == ItemObject.ItemTypeEnum.Banner && (this.ItemComponent is BannerComponent ? 1 : (this.StringId == "campaign_banner_small" ? 1 : 0)) == 0)
//        {
//          TaleWorlds.Library.Debug.FailedAssert("Banner item with name: " + (object) this.Name + " is not properly set. It must either be a campaign banner or it must have a banner component.", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (Deserialize), 747);
//          TaleWorlds.Library.Debug.Print("Banner item with name: " + (object) this.Name + " is not properly set. It must either be a campaign banner or it must have a banner component.", color: TaleWorlds.Library.Debug.DebugColor.Yellow);
//        }
//        XmlAttribute attribute16 = node.Attributes["AmmoOffset"];
//        if (attribute16 != null)
//        {
//          string[] strArray = attribute16.Value.Split(',');
//          this.WeaponComponent.PrimaryWeapon.SetAmmoOffset(new Vec3());
//          if (strArray.Length == 3)
//          {
//            try
//            {
//              this.WeaponComponent.PrimaryWeapon.SetAmmoOffset(new Vec3(float.Parse(strArray[0], (IFormatProvider) CultureInfo.InvariantCulture), float.Parse(strArray[1], (IFormatProvider) CultureInfo.InvariantCulture), float.Parse(strArray[2], (IFormatProvider) CultureInfo.InvariantCulture)));
//            }
//            catch (Exception ex)
//            {
//              TaleWorlds.Library.Debug.FailedAssert("[DEBUG]Throw Base Offset is not valid", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (Deserialize), 774);
//            }
//          }
//          else
//            TaleWorlds.Library.Debug.FailedAssert("[DEBUG]Throw Base Offset is not valid", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (Deserialize), 779);
//        }
//        if (node.Attributes["tier_override"] != null)
//          this.TierfOverride = float.Parse(node.Attributes["tier_override"].Value) + 1f;
//        this.Effectiveness = this.CalculateEffectiveness();
//        if (node.Attributes["value"] != null)
//          this.Value = int.Parse(node.Attributes["value"].Value);
//        else
//          this.DetermineValue();
//        if (this.PrimaryWeapon != null)
//        {
//          if (this.PrimaryWeapon.IsMeleeWeapon || this.PrimaryWeapon.IsRangedWeapon)
//          {
//            if (!string.IsNullOrEmpty(this.BodyName))
//              ;
//          }
//          else if (this.PrimaryWeapon.IsConsumable)
//          {
//            string.IsNullOrEmpty(this.HolsterBodyName);
//            if (!string.IsNullOrEmpty(this.BodyName))
//              ;
//          }
//          else if (this.PrimaryWeapon.IsShield)
//          {
//            if (!string.IsNullOrEmpty(this.BodyName))
//            {
//              int num = this.RecalculateBody ? 1 : 0;
//            }
//            string.IsNullOrEmpty(this.CollisionBodyName);
//          }
//        }
//      }
//      this.DetermineItemCategoryForItem();
//      Game.Current.ItemObjectDeserialized(this);
//    }

//    public ItemObject.ItemTypeEnum ItemType
//    {
//      get => this.Type;
//      private set => this.Type = value;
//    }

//    public bool IsMountable => this.HasHorseComponent && this.HorseComponent.IsRideable;

//    public bool IsTradeGood => this.ItemType == ItemObject.ItemTypeEnum.Goods;

//    public bool IsBannerItem => this.ItemType == ItemObject.ItemTypeEnum.Banner;

//    public bool IsAnimal => this.HasHorseComponent && !this.HorseComponent.IsRideable;

//    public override string ToString() => this.StringId;

//    public SkillObject RelevantSkill
//    {
//      get
//      {
//        SkillObject relevantSkill = (SkillObject) null;
//        if (this.PrimaryWeapon != null)
//          relevantSkill = this.PrimaryWeapon.RelevantSkill;
//        else if (this.HasHorseComponent)
//          relevantSkill = DefaultSkills.Riding;
//        return relevantSkill;
//      }
//    }

//    public static ItemObject GetItemFromWeaponKind(int weaponKind)
//    {
//      return weaponKind < 0 ? (ItemObject) null : MBObjectManager.Instance.GetObject(new MBGUID((uint) weaponKind)) as ItemObject;
//    }

//    [Conditional("_RGL_KEEP_ASSERTS")]
//    private void MakeSureProperFlagsSetForOneAndTwoHandedWeapons()
//    {
//      if (this.PrimaryWeapon == null)
//        return;
//      if ((this.Type == ItemObject.ItemTypeEnum.Bow || this.Type == ItemObject.ItemTypeEnum.Crossbow || this.Type == ItemObject.ItemTypeEnum.TwoHandedWeapon) && !this.PrimaryWeapon.WeaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.NotUsableWithOneHand))
//      {
//        TaleWorlds.Library.Debug.FailedAssert(this.Name.ToString() + ": Two Handed Item does not have NotUsableWithOneHand flag!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (MakeSureProperFlagsSetForOneAndTwoHandedWeapons), 957);
//        this.PrimaryWeapon.WeaponFlags |= WeaponFlags.NotUsableWithOneHand;
//      }
//      if ((this.Type == ItemObject.ItemTypeEnum.Bow || this.Type == ItemObject.ItemTypeEnum.Crossbow) && !this.PrimaryWeapon.WeaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.TwoHandIdleOnMount))
//      {
//        TaleWorlds.Library.Debug.FailedAssert(this.Name.ToString() + ": Two Handed Item does not have TwoHandIdleOnMount flag!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (MakeSureProperFlagsSetForOneAndTwoHandedWeapons), 966);
//        this.PrimaryWeapon.WeaponFlags |= WeaponFlags.TwoHandIdleOnMount;
//      }
//      if (this.Type != ItemObject.ItemTypeEnum.OneHandedWeapon && this.Type != ItemObject.ItemTypeEnum.Shield || !this.PrimaryWeapon.WeaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.NotUsableWithOneHand))
//        return;
//      TaleWorlds.Library.Debug.FailedAssert(this.Name.ToString() + ": One Handed Item has TwoHanded flag!", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.Core\\ItemObject.cs", nameof (MakeSureProperFlagsSetForOneAndTwoHandedWeapons), 975);
//      this.PrimaryWeapon.WeaponFlags &= ~WeaponFlags.NotUsableWithOneHand;
//    }

//    [Conditional("DEBUG")]
//    private void DebugMakeSurePhysicsMaterialCorrectlySet()
//    {
//    }

//    [Conditional("DEBUG")]
//    private void MakeSureWeaponLengthAndMissileSpeedCorrect()
//    {
//      if (this.WeaponComponent == null)
//        return;
//      foreach (WeaponComponentData weapon in (List<WeaponComponentData>) this.WeaponComponent.Weapons)
//      {
//        int weaponLength = weapon.WeaponLength;
//        if (this.Type == ItemObject.ItemTypeEnum.Arrows || this.Type == ItemObject.ItemTypeEnum.Bolts || this.Type == ItemObject.ItemTypeEnum.SlingStones || this.Type == ItemObject.ItemTypeEnum.Bullets || this.Type == ItemObject.ItemTypeEnum.Thrown)
//        {
//          int missileSpeed = weapon.MissileSpeed;
//        }
//      }
//    }

//    public static ItemObject.ItemTypeEnum GetAmmoTypeForItemType(ItemObject.ItemTypeEnum itemType)
//    {
//      switch (itemType)
//      {
//        case ItemObject.ItemTypeEnum.Bow:
//          return ItemObject.ItemTypeEnum.Arrows;
//        case ItemObject.ItemTypeEnum.Crossbow:
//          return ItemObject.ItemTypeEnum.Bolts;
//        case ItemObject.ItemTypeEnum.Sling:
//          return ItemObject.ItemTypeEnum.SlingStones;
//        case ItemObject.ItemTypeEnum.Thrown:
//          return ItemObject.ItemTypeEnum.Thrown;
//        case ItemObject.ItemTypeEnum.Pistol:
//          return ItemObject.ItemTypeEnum.Bullets;
//        default:
//          return ItemObject.ItemTypeEnum.Invalid;
//      }
//    }

//    public static float GetAirFrictionConstant(WeaponClass weaponClass, WeaponFlags weaponFlags)
//    {
//      switch (weaponClass)
//      {
//        case WeaponClass.Arrow:
//          return weaponFlags.HasAnyFlag<WeaponFlags>(WeaponFlags.MultiplePenetration) ? ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBallistaBolt) : ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
//        case WeaponClass.Bolt:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
//        case WeaponClass.SlingStone:
//        case WeaponClass.Cartridge:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBullet);
//        case WeaponClass.Bow:
//        case WeaponClass.Crossbow:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
//        case WeaponClass.Sling:
//        case WeaponClass.Stone:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionStone);
//        case WeaponClass.Boulder:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBoulder);
//        case WeaponClass.ThrowingAxe:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionAxe);
//        case WeaponClass.ThrowingKnife:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionKnife);
//        case WeaponClass.Javelin:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionJavelin);
//        case WeaponClass.Pistol:
//        case WeaponClass.Musket:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBullet);
//        case WeaponClass.BallistaBoulder:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBallistaBoulder);
//        case WeaponClass.BallistaStone:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionBallistaStone);
//        default:
//          return ManagedParameters.Instance.GetManagedParameter(ManagedParametersEnum.AirFrictionArrow);
//      }
//    }

//    private float CalculateEffectiveness()
//    {
//      float effectiveness = 1f;
//      ArmorComponent armorComponent = this.ArmorComponent;
//      if (armorComponent != null)
//        effectiveness = this.Type != ItemObject.ItemTypeEnum.HorseHarness ? (float) (((double) armorComponent.HeadArmor * 34.0 + (double) armorComponent.BodyArmor * 42.0 + (double) armorComponent.LegArmor * 12.0 + (double) armorComponent.ArmArmor * 12.0) * 0.029999999329447746) : (float) armorComponent.BodyArmor * 1.67f;
//      if (this.WeaponComponent != null)
//      {
//        WeaponComponentData primaryWeapon = this.WeaponComponent.PrimaryWeapon;
//        float num1 = 1f;
//        switch (primaryWeapon.WeaponClass)
//        {
//          case WeaponClass.Dagger:
//            num1 = 0.4f;
//            break;
//          case WeaponClass.OneHandedSword:
//            num1 = 0.55f;
//            break;
//          case WeaponClass.TwoHandedSword:
//            num1 = 0.6f;
//            break;
//          case WeaponClass.OneHandedAxe:
//            num1 = 0.5f;
//            break;
//          case WeaponClass.TwoHandedAxe:
//            num1 = 0.55f;
//            break;
//          case WeaponClass.Mace:
//            num1 = 0.5f;
//            break;
//          case WeaponClass.Pick:
//            num1 = 0.4f;
//            break;
//          case WeaponClass.TwoHandedMace:
//            num1 = 0.55f;
//            break;
//          case WeaponClass.OneHandedPolearm:
//            num1 = 0.4f;
//            break;
//          case WeaponClass.TwoHandedPolearm:
//            num1 = 0.4f;
//            break;
//          case WeaponClass.LowGripPolearm:
//            num1 = 0.4f;
//            break;
//          case WeaponClass.Arrow:
//            num1 = 3f;
//            break;
//          case WeaponClass.Bolt:
//            num1 = 3f;
//            break;
//          case WeaponClass.SlingStone:
//            num1 = 0.1f;
//            break;
//          case WeaponClass.Cartridge:
//            num1 = 3f;
//            break;
//          case WeaponClass.Bow:
//            num1 = 0.55f;
//            break;
//          case WeaponClass.Crossbow:
//            num1 = 0.57f;
//            break;
//          case WeaponClass.Sling:
//            num1 = 0.1f;
//            break;
//          case WeaponClass.Stone:
//          case WeaponClass.BallistaStone:
//            num1 = 0.1f;
//            break;
//          case WeaponClass.Boulder:
//          case WeaponClass.BallistaBoulder:
//            num1 = 0.1f;
//            break;
//          case WeaponClass.ThrowingAxe:
//            num1 = 0.25f;
//            break;
//          case WeaponClass.ThrowingKnife:
//            num1 = 0.2f;
//            break;
//          case WeaponClass.Javelin:
//            num1 = 0.28f;
//            break;
//          case WeaponClass.Pistol:
//            num1 = 1f;
//            break;
//          case WeaponClass.Musket:
//            num1 = 1f;
//            break;
//          case WeaponClass.SmallShield:
//            num1 = 0.4f;
//            break;
//          case WeaponClass.LargeShield:
//            num1 = 0.5f;
//            break;
//        }
//        if (primaryWeapon.IsRangedWeapon)
//          effectiveness = !primaryWeapon.IsConsumable ? (float) (((double) (primaryWeapon.MissileSpeed * primaryWeapon.MissileDamage) * 1.75 + (double) (primaryWeapon.ThrustSpeed * primaryWeapon.Accuracy) * 0.30000001192092896) * 0.0099999997764825821) * (float) primaryWeapon.MaxDataValue * num1 : (float) (((double) (primaryWeapon.MissileDamage * primaryWeapon.MissileSpeed) * 1.7749999761581421 + (double) (primaryWeapon.Accuracy * (int) primaryWeapon.MaxDataValue) * 25.0 + (double) primaryWeapon.WeaponLength * 4.0) * 0.0069439997896552086) * (float) primaryWeapon.MaxDataValue * num1;
//        else if (primaryWeapon.IsMeleeWeapon)
//        {
//          float b = (float) (primaryWeapon.ThrustSpeed * primaryWeapon.ThrustDamage) * 0.01f;
//          double a = (double) (primaryWeapon.SwingSpeed * primaryWeapon.SwingDamage) * 0.0099999997764825821;
//          float num2 = MathF.Max((float) a, b);
//          float num3 = MathF.Min((float) a, b);
//          effectiveness = (float) ((((double) num2 + (double) num3 * (double) num3 / (double) num2) * 120.0 + (double) primaryWeapon.Handling * 15.0 + (double) primaryWeapon.WeaponLength * 20.0 + (double) this.Weight * 5.0) * 0.0099999997764825821) * num1;
//        }
//        else if (primaryWeapon.IsConsumable)
//          effectiveness = (float) (((double) primaryWeapon.MissileDamage * 550.0 + (double) primaryWeapon.MissileSpeed * 15.0 + (double) primaryWeapon.MaxDataValue * 60.0) * 0.0099999997764825821) * num1;
//        else if (primaryWeapon.IsShield)
//          effectiveness = (float) (((double) primaryWeapon.BodyArmor * 60.0 + (double) primaryWeapon.ThrustSpeed * 10.0 + (double) primaryWeapon.MaxDataValue * 40.0 + (double) primaryWeapon.WeaponLength * 20.0) * 0.0099999997764825821) * num1;
//      }
//      if (this.HorseComponent != null)
//        effectiveness = (float) (((double) (this.HorseComponent.ChargeDamage * this.HorseComponent.Speed + this.HorseComponent.Maneuver * this.HorseComponent.Speed) + (double) this.HorseComponent.BodyLength * (double) this.Weight * 0.02500000037252903) * (double) (this.HorseComponent.HitPoints + this.HorseComponent.HitPointBonus) * 9.9999997473787516E-05);
//      return effectiveness;
//    }

//    internal void DetermineValue()
//    {
//      ItemValueModel itemValueModel = Game.Current.BasicModels.ItemValueModel;
//      this.Value = itemValueModel != null ? itemValueModel.CalculateValue(this) : 1;
//    }

//    public WeaponComponentData GetWeaponWithUsageIndex(int usageIndex)
//    {
//      return this.Weapons.ElementAt<WeaponComponentData>(usageIndex);
//    }

//    public enum ItemUsageSetFlags
//    {
//      RequiresMount = 1,
//      RequiresNoMount = 2,
//      RequiresShield = 4,
//      RequiresNoShield = 8,
//      PassiveUsage = 16, // 0x00000010
//    }

//    public enum ItemTypeEnum
//    {
//      Invalid,
//      Horse,
//      OneHandedWeapon,
//      TwoHandedWeapon,
//      Polearm,
//      Arrows,
//      Bolts,
//      SlingStones,
//      Shield,
//      Bow,
//      Crossbow,
//      Sling,
//      Thrown,
//      Goods,
//      HeadArmor,
//      BodyArmor,
//      LegArmor,
//      HandArmor,
//      Pistol,
//      Musket,
//      Bullets,
//      Animal,
//      Book,
//      ChestArmor,
//      Cape,
//      HorseHarness,
//      Banner,
//    }

//    public enum ItemTiers
//    {
//      Tier1,
//      Tier2,
//      Tier3,
//      Tier4,
//      Tier5,
//      Tier6,
//      NumTiers,
//    }
//  }
//}
