//// Decompiled with JetBrains decompiler
//// Type: TaleWorlds.Core.WeaponComponent
//// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//// MVID: 4282646E-E702-4B98-B76A-B7486FBD2594
//// Assembly location: C:\Users\trist\Documents\Modding\Bannerlord\DLLs\TaleWorlds.Core.dll

//using System.Collections.Generic;
//using System.Xml;
//using TaleWorlds.Library;
//using TaleWorlds.ObjectSystem;

//#nullable disable
//namespace TaleWorlds.Core
//{
//  public class WeaponComponent : ItemComponent
//  {
//    private readonly MBList<WeaponComponentData> _weaponList = new MBList<WeaponComponentData>();

//    internal static void AutoGeneratedStaticCollectObjectsWeaponComponent(
//      object o,
//      List<object> collectedObjects)
//    {
//      ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
//    }

//    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
//    {
//      base.AutoGeneratedInstanceCollectObjects(collectedObjects);
//    }

//    public MBReadOnlyList<WeaponComponentData> Weapons
//    {
//      get => (MBReadOnlyList<WeaponComponentData>) this._weaponList;
//    }

//    public WeaponComponentData PrimaryWeapon => this._weaponList[0];

//    public void AddWeapon(
//      WeaponComponentData weaponComponentData,
//      ItemModifierGroup itemModifierGroup)
//    {
//      this.ItemModifierGroup = itemModifierGroup;
//      this._weaponList.Add(weaponComponentData);
//    }

//    public override ItemComponent GetCopy() => (ItemComponent) new WeaponComponent(this.Item);

//    public WeaponComponent(ItemObject item) => this.Item = item;

//    public ItemObject.ItemTypeEnum GetItemType()
//    {
//      return WeaponComponentData.GetItemTypeFromWeaponClass(this._weaponList[0].WeaponClass);
//    }

//    public override void Deserialize(MBObjectManager objectManager, XmlNode node)
//    {
//      base.Deserialize(objectManager, node);
//      XmlAttribute attribute = node.Attributes["modifier_group"];
//      if (attribute != null)
//      {
//        string str = attribute.Value;
//      }
//      WeaponComponentData weaponComponentData = new WeaponComponentData(this.Item);
//      weaponComponentData.Deserialize(this.Item, node);
//      this._weaponList.Add(weaponComponentData);
//    }
//  }
//}
